# properties 는 계층구조의 중복 발생
# yml ,yaml 을 통해서 들여쓰기 계충구조 사용

#port
#server:
#  port:8081

#database 연동 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234
  jpa :
    database: mysql
    # innoDB 사용 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    # 테이블은 생성해주나 스키마는 반드시 사전에 생성해주어야 함.
    generate-ddl : true
    # JPA는 인터페이스 이고 HIBERNATE는 구현체이다.(실직적 기능 구현)
    hibernate:
      # CREATE 옵션은 매변 테이블을 드랍하고 재 생성하는 옵션
      # UPDATE 옵션은 변경사항만 ALTER 하고 기존의 데이터 유지 -> 변경사항 중 주로 추가 사항만을 반영하고 삭제나 수정사항은 반영x 경우 多
      # VALIDATE 옵션은 실제 DB와의 차이만을 CHECK
      ddl-auto:
    # 콘솔창에 ddl, dml 문을 출력하여 보여주는 옵션
    show_sql : true
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
